### ISSUE TITLE
tried and get this

### ISSUE THREAD

**Issue by rchiileea** [flobz/psacc-ha-beta#1]
![image](https://user-images.githubusercontent.com/87599807/174448947-10c6ee26-910b-4d9e-8a0a-77e71fa6c013.png)

**Comment by rchiileea** [comment]
so tested latest release in contatiner and it works fine, just no HA version wont load and is stuck on loading screen

**Comment by alloro72** [comment]
It should be an issue with ingress, please fix it

**Comment by flobz** [comment]
Duplicate
